name: dart_tinydtls
description: Dart ffi bindings to the tinydtls library.
version: 0.1.0
homepage: https://github.com/namib-project/dart_tinydtls

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ffigen: ^4.1.2
  dart_code_metrics: ^4.11.0

ffigen:
  name: TinyDTLS
  description: ffi binding to the tinydtls library.
  output: 'lib/src/ffi/generated_bindings.dart'
  # NOTE: This directory may be different depending on your system.
  compiler-opts: '-I/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include -I./third_party/tinydtls'
  headers:
    entry-points:
      - 'third_party/tinydtls/dtls.h'
    include-directives:
      - '**dtls.h'
      - '**dtls_config.h'
      - '**session.h'
      - '**state.h'
      - '**alert.h'
      - '**crypto.h'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names
    // ignore_for_file: constant_identifier_names, public_member_api_docs
    // ignore_for_file: unused_field, lines_longer_than_80_chars
  # The following is roughly based on Rust library `tinydtls-sys`'s inclusions.
  functions:
    include:
      - "dtls_.*"
      - "DTLS_.*"
      - "memxor"
      - "equals"
      - "WITH_.*"
      - "PACKAGE_.*"
      - "netq_.*"
      - "NETQ_.*"
    exclude:
      - "dtls_set_handler"
  structs:
    include:
      - "dtls_.*"
      - "DTLS_.*"
      - "seqnum_t"
      - "__attribute__"
      - "clock_time_t"
      - "WITH_.*"
      - "PACKAGE_.*"
      - "netq_.*"
      - "NETQ_.*"
      - "session_t"
    exclude:
      - "dtls_hello_verify_t"
    enums:
      include:
        - "dtls_.*"
        - "DTLS_.*"
        - "seqnum_t"
        - "__attribute__"
        - "clock_time_t"
        - "WITH_.*"
        - "PACKAGE_.*"
        - "netq_.*"
        - "NETQ_.*"
        - "session_t"
    vars:
      include:
        - "dtls_.*"
        - "DTLS_.*"
        - "CLOCK_SECOND"
        - "TLS_.*"
        - "DTLSv12"
        - "WITH_.*"
        - "PACKAGE_.*"
        - "netq_.*"
        - "NETQ_.*"
